### PR TITLE
Matching organisations scripts

### PR DESCRIPTION
**Pull request by ramGranell**
I am a developer from [FAIRsharing.org](https://fairsharing.org/) that has been using ROR organisations for a while. We have talk to A. French from ROR that suggested us to add the scripts that we have been using to match [our organisations](https://fairsharing.org/organisations/) to ROR organisations. The code is generic enough to be used with any organisations meanwhile you have their name and/or homepage in a text file. 

It is the first time that I do a PR to any external repository and not sure if the code is documented and organised enough  to be accepted. Feel free to modify anything you consider.

### CODE REVIEW

**Comment by amandafrench** [comment]
Thanks so much, @ramGranell! Really appreciate it. We'll take a look and let you know if we need more documentation.

**Review by amandafrench — COMMENTED** [review]
Note that the package numpy is required

**Comment by lizkrznarich** [comment]
Hi @ramGranell , thanks so much! Your code was add into @amandafrench 's branch and merged on https://github.com/ror-community/ror-utilities/pull/8, so I'm closing this PR.

**Comment by amandafrench** [comment]
Yes, thanks so much, @ramGranell!! Your scripts are now in https://github.com/ror-community/ror-utilities/tree/main/fairsharing-match-scripts . Will add a link to the forthcoming blog post.

**Pull request closed without merging**
